<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_projects"
 *
 * Auto generated by Extension Builder 2015-05-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
	'title' => 'RKW DataProtection',
	'description' => 'Extension for Compliance with General Data Protection Regulation (GDPR),
	'category' => 'plugin',
	'author' => 'Steffen Kroggel',
	'author_email' => 'developer@steffenkroggel.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '8.7.0',
	'constraints' => [
		'depends' => [
			'typo3' => '7.6.0-7.6.99',
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
];
